# let mac detect emoji shortcut
map cmd+e no_op

# make 'option + arrow key' work on tmux
map alt+left send_text all \x1bb
map alt+right send_text all \x1bf

# clear scrollback buffer
map cmd+k combine : clear_terminal to_cursor active : clear_terminal scrollback active

# make M-< (go to top) work
map alt+shift+, send_text all \x1b<
map alt+shift+. send_text all \x1b>

# don't ask when reading from clipboard
clipboard_control write-clipboard read-clipboard

# option as meta key
macos_option_as_alt yes

# make scrollback bigger
scrollback_lines 50000

# use system's default shell
shell .

editor              nvim
font_family         Comic Code
font_size           20.0
bold_font           auto
italic_font         auto
bold_italic_font    auto

# BEGIN_KITTY_THEME
# 1984 Orwellian
include current-theme.conf
# END_KITTY_THEME
